- name: bug
  description: Something isn't working
  color: d42a34

- name: blocked
  description: Cannot address this till other issues are solved first
  color: e0b063

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: ffD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: release
  description: Anything related to an incoming release
  color: ffffff
