# Copyright (C) 2024 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# action derived from ansys/actions/tests-pytest
name: 'Run the test suite for a given version of Ansys SCADE'

description: >
  The ``scade-tests-pytest`` action runs the test suite for a Python library
  and a given version of Ansys SCADE using
  `pytest <https://docs.pytest.org/en/stable/>`_.
  This action accepts markers, options, and post arguments to pass to
  ``pytest`` before executing the test session.

inputs:

  scade-version:
    description: >
      SCADE version used for installing and running ``pytest``.
      For example, use ``'24.1'`` for Ansys SCADE 2024 R1.
    required: true

  # Optional inputs
  library-dir:
    description: >
      Directory of the library to test.
    default: '.'
    required: false

  pytest-markers:
    description: >
      Set of `pytest markers
      <https://docs.pytest.org/en/stable/example/markers.html>`_ in the form of
      a string. These markers are used to discretize tests when running the test
      session.
    default: ''
    required: false

  pytest-extra-args:
    description: >
      Set of additional ``pytest`` arguments in the form of a string.
    default: ''
    required: false

  pytest-postargs:
    description: >
      Directory of the test suite and the level of verbosity.
    default: 'tests -vv'
    required: false

  checkout:
    description: >
      Whether to clone the repository on the CI/CD machine.
    default: 'true'
    required: false


runs:
  using: "composite"
  steps:

    - name: "Get SCADE installation directory"
      id: get-scade-dir
      uses: jenseng/dynamic-uses@5175289a9a87978dcfcb9cf512b821d23b2a53eb # v1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: ansys/scade-actions/get-scade-dir@${{ github.repository == 'ansys/scade-actions' && github.sha || env.action_ref }}
        with: |
          {
            "scade-version": ${{ inputs.scade-version }}
          }

    - name: "Get SCADE Python interpreter"
      id: get-scade-python
      uses: jenseng/dynamic-uses@5175289a9a87978dcfcb9cf512b821d23b2a53eb # v1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: ansys/scade-actions/get-scade-python@${{ github.repository == 'ansys/scade-actions' && github.sha || env.action_ref }}
        with: |
          {
            "scade-dir": ${{ toJSON(fromJSON(steps.get-scade-dir.outputs.outputs).scade-directory) }}
          }

    - name: "Create Python virtual environment"
      id: create-scade-venv
      uses: jenseng/dynamic-uses@5175289a9a87978dcfcb9cf512b821d23b2a53eb # v1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: ansys/scade-actions/create-scade-venv@${{ github.repository == 'ansys/scade-actions' && github.sha || env.action_ref }}
        with: |
          {
            "python-dir": ${{ toJSON(fromJSON(steps.get-scade-python.outputs.outputs).python-dir) }},
            "target-dir": ".venvs",
            "target-name": "${{ fromJSON(steps.get-scade-python.outputs.outputs).python-name }}"
          }

    - name: "Run the tests"
      uses: jenseng/dynamic-uses@5175289a9a87978dcfcb9cf512b821d23b2a53eb # v1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: ansys/scade-actions/tests-pytest@${{ github.repository == 'ansys/scade-actions' && github.sha || env.action_ref }}
        with: |
          {
            "python-dir": ${{ toJSON(fromJSON(steps.create-scade-venv.outputs.outputs).scripts-dir) }},
            "library-dir": ${{ inputs.library-dir }},
            "pytest-markers": ${{ inputs.pytest-markers }},
            "pytest-extra-args": ${{ inputs.pytest-extra-args }},
            "pytest-postargs": ${{ inputs.pytest-postargs }},
            "checkout": ${{ inputs.checkout }}
          }
