# Copyright (C) 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# suite-code
name: 'Generate the code of a SCADE Suite model'

description: >
  The ``suite-code`` action executes ``scade.exe -code`` on a SCADE Suite project
  for a given configuration.

inputs:

  scade-dir:
    description: >
      Ansys SCADE installation directory.
    required: true

  project:
    description: >
      Path of the SCADE Suite project.
    required: true

  configuration:
    description: >
      Configuration to use for generating the code.
    required: true

  # Optional inputs
  build:
    description: >
      Whether ``scade.exe`` -code shall be called with the option ``-sim``
      to build the generated code.
    default: 'false'
    required: false

  archive:
    description: >
      Path of the zip archive to contain the target directory.
    default: ''
    required: false

  checkout:
    description: >
      Whether to clone the repository on the CI/CD machine.
    default: 'true'
    required: false

outputs:

  target-directory:
    description: >
      Path of the target directory where the code is generated.
    value: ${{ steps.get.outputs.target-directory }}

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}

    - name: "Retrieve target directory for the configuration"
      shell: cmd
      id: get
      run: |
        :: get_target_dir.py echoes on stdout target-directory=<computed directory>
        "${{ inputs.scade-dir }}\SCADE\bin\scade.exe" -script "${{ inputs.project }}" "${{ github.action_path }}\get_target_dir.py" "main('${{ inputs.configuration }}')" >> %GITHUB_OUTPUT%

    - name: "Generate code"
      shell: cmd
      id: code
      run: |
        :: Call GenerateCode.bat
        call "${{ github.action_path }}\GenerateCode.bat" "${{ inputs.scade-dir }}" "${{ inputs.project }}" "${{ inputs.configuration }}" "${{ inputs.build }}"

    - name: "Archive the generated code"
      shell: powershell
      if: ${{ inputs.archive }}
      run: |
        # zip generated code for delivery
        if (test-path "${{ inputs.archive }}") { del "${{ inputs.archive }}" }
        Compress-Archive -Path "${{ steps.get.outputs.target-directory }}\*.*" -DestinationPath "${{ inputs.archive }}"
