name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  DOCUMENTATION_CNAME: 'actions.scade.docs.pyansys.com'
  test-library-name: 'ansys-scade-actions'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  labeler:
    name: "Label syncer"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label based on changed files
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          startsWith(github.event.pull_request.head.ref, 'doc') ||
          startsWith(github.event.pull_request.head.ref, 'docs')
        with:
          labels: documentation

      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          startsWith(github.event.pull_request.head.ref, 'maint') ||
          startsWith(github.event.pull_request.head.ref, 'no-ci') ||
          startsWith(github.event.pull_request.head.ref, 'ci')
        with:
          labels: maintenance

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.event.pull_request.head.ref, 'feat')
        with:
          labels: |
            enhancement

      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          startsWith(github.event.pull_request.head.ref, 'fix') ||
          startsWith(github.event.pull_request.head.ref, 'patch')
        with:
          labels: bug

      - name: Suggest to add labels
        uses: peter-evans/create-or-update-comment@v4
        if: toJSON(github.event.pull_request.labels.*.name) == '{}'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please add one of the following labels to add this contribution to the Release Notes :point_down:
            - [bug](https://github.com/ansys/scade-actions/pulls?q=label%3Abug+)
            - [documentation](https://github.com/ansys/scade-actions/pulls?q=label%3Adocumentation+)
            - [enhancement](https://github.com/ansys/scade-actions/pulls?q=label%3Aenhancement+)
            - [good first issue](https://github.com/ansys/scade-actions/pulls?q=label%3Agood+first+issue)
            - [maintenance](https://github.com/ansys/scade-actions/pulls?q=label%3Amaintenance+)
            - [release](https://github.com/ansys/scade-actions/pulls?q=label%3Arelease+)

  commit-and-branch-style:
    name: "Commit and branch style"
    runs-on: ubuntu-latest
    needs: labeler
    steps:
      - name: "Check commit style"
        uses: ansys/actions/commit-style@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check branch naming convention"
        uses: ansys/actions/branch-name-style@v6

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    needs: commit-and-branch-style
    steps:
      - name: "Run code style checks"
        uses: ansys/actions/code-style@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false

      - name: "Verify private actions are not pointing to the 'main' branch"
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        run: |
          if $(grep -q --exclude-dir={.git,.github,doc} "ansys\/actions\/.*\@main" -r .); then
            echo -e "\033[1;91m[ERROR]: Found private actions pointing to the 'main' branch.\033[0m"
            grep -q --exclude-dir={.git,.github,doc} "ansys\/actions\/.*\@main" -r .
          fi

  doc-style:
    name: "Doc style"
    runs-on: ubuntu-latest
    needs: commit-and-branch-style
    steps:
      - name: "Run documentation style checks"
        uses: ansys/actions/doc-style@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-build:
    name: "Doc build"
    runs-on: ubuntu-latest
    needs: doc-style
    steps:
      - name: "Build documentation"
        uses: ansys/actions/doc-build@v6
        with:
          skip-install: true
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          dependencies: "texlive-fonts-extra qpdf"

  python-tests:
    # tests for python actions
    name: "Python Tests"
    needs: [doc-build]
    runs-on: [self-hosted, 'SCADE']
    strategy:
      matrix:
        scade-version: ['23.2']
      fail-fast: false
    steps:
      - name: "Execute setup.py tests"
        uses: ./scade-tests-pytest
        with:
          scade-version: ${{ matrix.scade-version }}
          library-dir: "tests/python-setup"
          pytest-postargs: "tests/python-setup/tests -vv"
          checkout: false

      - name: "Execute pyproject tests"
        uses: ./scade-tests-pytest
        with:
          scade-version: ${{ matrix.scade-version }}
          library-dir: "tests/python-pyproject"
          pytest-postargs: "tests/python-pyproject/tests -vv"
          checkout: false

  unit-tests:
    # tests for Python code included in actions
    name: "Unit Tests"
    runs-on: [self-hosted, 'SCADE']
    strategy:
      matrix:
        scade-version: ['23.2']
      fail-fast: false
    steps:
      - name: "Install Git and clone project"
        uses: actions/checkout@v4

      - name: "Run Python unit tests"
        uses: ./scade-tests-pytest
        with:
          checkout: false
          pytest-extra-args: "--ignore=tests/python-pyproject --ignore=tests/python-setup --basetemp=tmp --cov-report=term --cov-branch --cov-report=html:.cov/html --cov-report=xml:.cov/xml"
          scade-version: ${{ matrix.scade-version }}

      # - name: "Upload coverage reports to Codecov"
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: ansys/scade-actions
      #     files: .cov/xml

  suite-tests:
    # tests for SCADE Suite actions
    name: "Suite Tests"
    runs-on: [self-hosted, 'SCADE']
    strategy:
      matrix:
        scade-version: ['23.2']
      fail-fast: false
    steps:
      - name: "Check out the repository"
        uses: actions/checkout@v4

      - name: "Get SCADE installation directory"
        uses: ./get-scade-dir
        id: get-scade-dir
        with:
          scade-version: ${{ matrix.scade-version }}

      - name: "Generate with suite-code"
        uses: ./suite-code
        id: suite-code-generate
        with:
          scade-dir: ${{ steps.get-scade-dir.outputs.scade-directory }}
          project: "tests/suite-code/Model/Model.etp"
          configuration: "Suite Code"
          build: "false"
          checkout: false

      - name: "Upload code target directory to artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "code-target-directory"
          path: "${{ steps.suite-code-generate.outputs.target-directory }}/*.*"
          retention-days: 7
          if-no-files-found: error

      - name: "Build with suite-code"
        uses: ./suite-code
        id: suite-code-build
        with:
          scade-dir: ${{ steps.get-scade-dir.outputs.scade-directory }}
          project: "tests/suite-code/Model/Model.etp"
          configuration: "Simulation"
          build: "true"
          checkout: false

      - name: "Log the target directories"
        shell: cmd
        run: |
          echo Generation target directory: ${{ steps.suite-code-generate.outputs.target-directory }}
          echo Build target directory: ${{ steps.suite-code-build.outputs.target-directory }}

  tests:
    name: "All Tests"
    needs: [python-tests, unit-tests, suite-tests]
    runs-on: ubuntu-latest
    steps:
      - name: "Synchronization"
        run: |
          echo Tests completed

  doc-deploy-dev:
    name: "Deploy developers documentation"
    needs: [doc-build, tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags')
    steps:
      - uses: ansys/actions/doc-deploy-dev@v6
        with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: "Release to GitHub"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [doc-build, tests]
    steps:

    - name: "Download HTML documentation"
      uses: actions/download-artifact@v4
      with:
        name: documentation-html
        path: documentation-html

    - name: "Zip HTML documentation"
      uses: vimtor/action-zip@v1.2
      with:
        files: documentation-html
        dest: documentation-html.zip

    - name: "Download PDF documentation"
      uses: actions/download-artifact@v4
      with:
        name: documentation-pdf
        path: documentation-pdf

    - name: "Zip PDF documentation"
      uses: vimtor/action-zip@v1.2
      with:
        files: documentation-pdf
        dest: documentation-pdf.zip

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          documentation-html.zip
          documentation-pdf.zip

  doc-deploy-stable:
    name: "Upload stable documentation"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: ansys/actions/doc-deploy-stable@v6
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
